language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t dilshadcp/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true dilshadcp/react-test npm test -- --coverage

after_success:
  - docker build -t dilshadcp/multi-client ./client
  - docker build -t dilshadcp/multi-nginx ./nginx
  - docker build -t dilshadcp/multi-server ./server
  - docker build -t dilshadcp/multi-worker ./worker
  #login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to dockerhub
  - docker push dilshadcp/multi-client
  - docker push dilshadcp/multi-nginx
  - docker push dilshadcp/multi-server
  - docker push dilshadcp/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-513429949438'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

